version: "3.8"

services:

  mongodb:
    image: mongo:6.0.2
    restart: always    
    environment:
      - MONGO_INITDB_DATABASE=datosSaliclor
      - MONGO_INITDB_ROOT_USERNAME=root      
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - ./deploy/.data:/data/db
    networks:
      - local

  api:
    depends_on:
      - mongodb
    build: ./APIRest
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - DB_HOST=mongodb
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_NAME=datosSaliclor
      - DB_PORT=27017
    stdin_open: true
    tty: true
    networks:
      - local

networks:
  local: