version: "3.8"

services:

  mongodb:
    image: mongo:6.0.2
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=saliclor-db
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - ./deploy/.data:/data/db
    networks:
      - local

  api:
    depends_on:
      - mongodb
    build: ./api
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=saliclor-db
      - DB_USER=username
      - DB_PASSWORD=password
    stdin_open: true
    tty: true
    networks:
      - local

networks:
  local: