version: "3.8"

services:
  mongodb:
    image: mongo:6.0.2
    restart: unless-stopped
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=datosSaliclor
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
      - ./mongod.conf:/etc/mongod.conf
    entrypoint: ["mongod","--config","/etc/mongod.conf"]
  api:
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - DB_HOST=mongodb
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_NAME=datosSaliclor
      - DB_PORT=27017
    stdin_open: true
    tty: true

volumes:
  db: